sudo: required
services:
  - docker

before_install:
  - docker build -t senuch/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true senuch/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  environment: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-250764893382"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
